-- HOBBY TABLE
INSERT INTO HOBBY (NAME) 
VALUES ('Swimming');

INSERT INTO HOBBY (NAME) 
VALUES ('Jogging');

INSERT INTO HOBBY (NAME) 
VALUES ('Programming');

INSERT INTO HOBBY (NAME) 
VALUES ('Movies');

INSERT INTO HOBBY (NAME) 
VALUES ('Reading');


-- CONTACT TABLE
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Clarence', 'Ho', '1980-07-30');

INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Mikalai', 'Churakou', '1988-01-23');

INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Scott', 'Tiger', '1990-11-02');


-- TELEPHON TABLE
INSERT INTO TELEPHON (CONTACT_ID, TEL_TYPE, TEL_NUMBER) 
VALUES (1, 'Mobile', '1234567890');

INSERT INTO TELEPHON (CONTACT_ID, TEL_TYPE, TEL_NUMBER) 
VALUES (1, 'Home', '1234567890');

INSERT INTO TELEPHON (CONTACT_ID, TEL_TYPE, TEL_NUMBER) 
VALUES (2, 'Home', '1234567890');


-- CONTACT_HOBBY TABLE

INSERT INTO CONTACT_HOBBY(CONTACT_ID, HOBBY_ID)
VALUES (1, 1);

INSERT INTO CONTACT_HOBBY(CONTACT_ID, HOBBY_ID)
VALUES (1, 4);

INSERT INTO CONTACT_HOBBY(CONTACT_ID, HOBBY_ID)
VALUES (2, 1);
