-- HOBBY TABLE
INSERT INTO HOBBY (NAME) 
VALUES ('Swimming');

INSERT INTO HOBBY (NAME) 
VALUES ('Jogging');

INSERT INTO HOBBY (NAME) 
VALUES ('Programming');

INSERT INTO HOBBY (NAME) 
VALUES ('Movies');

INSERT INTO HOBBY (NAME) 
VALUES ('Reading');



